import { StyleSheet } from "react-native";

import { COLORS, RADIUS } from "~/constants/DesignSystem";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  statsBackground: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "#000000",
  },
  profilePager: {
    flex: 1,
  },
  profileBodyStack: {
    flex: 1,
    position: "relative",
  },
  profileBodyLayer: {
    ...StyleSheet.absoluteFill,
  },
  profileTabPage: {
    flex: 1,
  },
  profilePageSwipeZone: {
    height: 12,
  },
  topHeaderRow: {
    minHeight: 56,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
  },
  topAvatarButton: {
    width: 44,
    height: 44,
    position: "relative",
  },
  topAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.SURFACE_MUTED,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  topAvatarImage: {
    width: "100%",
    height: "100%",
    transform: [{ scale: 1.08 }],
  },
  topAvatarEditBadge: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.PURE_BLACK,
    borderWidth: 2,
    borderColor: COLORS.SURFACE,
  },
  topAvatarText: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.PURE_WHITE,
  },
  topHeaderTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.TEXT_PRIMARY,
    letterSpacing: -0.5,
  },
  topBalancePill: {
    backgroundColor: COLORS.PURE_BLACK,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 999,
  },
  topBalanceText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.PURE_WHITE,
  },
  heroCard: {
    marginHorizontal: 16,
    marginTop: 14,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: RADIUS.card,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  heroModeToggle: {
    width: 120,
    height: 32,
    borderRadius: RADIUS.chip,
    overflow: "hidden",
  },
  heroModePressTarget: {
    flex: 1,
    justifyContent: "center",
  },
  heroModePressed: {
    opacity: 0.76,
  },
  heroModeThumb: {
    position: "absolute",
    left: 5,
    top: 4,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.24)",
  },
  heroModeLabelViewport: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  heroModeLabel: {
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  heroRegionPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: RADIUS.chip,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  heroRegionText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.PURE_WHITE,
    letterSpacing: 0.6,
  },
  heroNameRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 12,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: COLORS.PURE_WHITE,
  },
  heroTagPill: {
    marginLeft: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: RADIUS.chip,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  heroTagText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.PURE_WHITE,
    letterSpacing: 0.3,
  },
  heroSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: "rgba(255,255,255,0.78)",
  },
  heroSubtitleViewport: {
    overflow: "hidden",
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  heroMetaPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: RADIUS.chip,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  heroMetaText: {
    marginLeft: 6,
    fontSize: 11,
    fontWeight: "600",
    color: COLORS.PURE_WHITE,
  },
  heroStatsRow: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  heroStatsViewport: {
    position: "relative",
    height: 64,
    marginTop: 12,
  },
  heroStatCard: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 18,
    borderWidth: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  heroStatLabelRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  heroStatIconViewport: {
    position: "relative",
    width: 15,
    height: 15,
  },
  heroStatIconLayer: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
  },
  heroStatIcon: {
    width: 14,
    height: 14,
  },
  heroStatLabel: {
    marginLeft: 6,
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255,255,255,0.72)",
  },
  playerStatLabel: {
    color: "rgba(255,255,255,0.78)",
  },
  heroStatValue: {
    marginTop: 8,
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.PURE_WHITE,
  },
  heroRankRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 10,
    height: 64,
  },
  pageScroll: {
    flex: 1,
  },
  pageScrollContent: {
    paddingBottom: 32,
  },
  pageBody: {
    paddingHorizontal: 16,
  },
  pageStatus: {
    minHeight: 240,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerModalContainer: {
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  pickerSheet: {
    maxHeight: "82%",
    borderRadius: 28,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
  },
  pickerHandle: {
    alignSelf: "center",
    width: 52,
    height: 5,
    borderRadius: 999,
    backgroundColor: COLORS.BORDER,
    marginBottom: 14,
  },
  pickerHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  pickerHeaderText: {
    flex: 1,
    paddingRight: 12,
  },
  pickerTitle: {
    fontSize: 18,
    fontWeight: "700",
  },
  pickerSubtitle: {
    marginTop: 4,
    fontSize: 13,
  },
  pickerCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  pickerErrorText: {
    marginBottom: 12,
    color: "#9b3f3f",
    fontSize: 13,
    fontWeight: "600",
  },
  identityPickerSearch: {
    minHeight: 44,
    marginBottom: 12,
    borderRadius: 8,
    elevation: 0,
    borderWidth: 1,
  },
  identityPlayerCardOption: {
    width: "48%",
    borderRadius: 8,
    borderWidth: 1,
    padding: 8,
    marginBottom: 12,
  },
  identityPlayerCardVisual: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 6,
    overflow: "hidden",
    position: "relative",
  },
  identityPlayerCardImage: {
    width: "100%",
    height: "100%",
  },
  identityPickerSelectedBadge: {
    position: "absolute",
    right: 7,
    top: 7,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  identityPlayerCardName: {
    minHeight: 34,
    marginTop: 8,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
  },
  identityTitleListContent: {
    paddingBottom: 8,
  },
  identityTitleOption: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 8,
  },
  identityTitleOptionText: {
    flex: 1,
    paddingRight: 12,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "700",
  },
  expressionPickerTabs: {
    flexDirection: "row",
    borderRadius: RADIUS.chip,
    borderWidth: 1,
    padding: 4,
    marginBottom: 12,
  },
  expressionPickerTab: {
    flex: 1,
    minHeight: 40,
    borderRadius: RADIUS.chip,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  expressionPickerTabText: {
    fontSize: 13,
    fontWeight: "700",
  },
  pickerList: {
    minHeight: 240,
  },
  pickerListContent: {
    paddingBottom: 8,
  },
  pickerGridRow: {
    justifyContent: "space-between",
  },
  pickerEmptyState: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  pickerEmptyText: {
    fontSize: 13,
    textAlign: "center",
  },
  pickerOptionCard: {
    width: "48%",
    borderRadius: 22,
    borderWidth: 1,
    padding: 12,
    marginBottom: 12,
  },
  pickerOptionVisual: {
    height: 104,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    marginBottom: 10,
  },
  pickerOptionImage: {
    width: "100%",
    height: "100%",
  },
  pickerOptionTitle: {
    fontSize: 13,
    fontWeight: "700",
  },
  pickerOptionSubtitle: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "600",
  },
  pickerChipHintRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 2,
  },
  pickerChipHint: {
    width: 16,
    height: 16,
    borderRadius: 8,
    overflow: "hidden",
    marginRight: 4,
    borderWidth: 1,
    borderColor: "rgba(23,26,31,0.08)",
  },
  pickerChipHintImage: {
    width: "100%",
    height: "100%",
  },
  pickerChipHintMore: {
    minWidth: 22,
    height: 16,
    paddingHorizontal: 5,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.72)",
    marginRight: 4,
    borderWidth: 1,
    borderColor: "rgba(23,26,31,0.08)",
  },
  pickerChipHintMoreText: {
    fontSize: 10,
    fontWeight: "700",
  },
  pickerChipHintText: {
    marginLeft: 4,
    fontSize: 10,
    fontWeight: "600",
  },
  pickerOptionMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  pickerOptionBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: RADIUS.chip,
    borderWidth: 1,
    marginRight: 6,
    marginBottom: 6,
  },
  pickerOptionDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginRight: 6,
  },
  pickerOptionBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  pickerSelectedText: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "700",
  },
  chromaPanel: {
    marginTop: 12,
    borderRadius: 20,
    borderWidth: 1,
    padding: 12,
    position: "relative",
  },
  chromaPanelClose: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 28,
    height: 28,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    zIndex: 1,
  },
  chromaPanelTitle: {
    fontSize: 14,
    fontWeight: "700",
    paddingRight: 34,
  },
  chromaPanelSubtitle: {
    marginTop: 2,
    fontSize: 12,
    paddingRight: 34,
  },
  chromaChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  chromaChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: RADIUS.chip,
    borderWidth: 1,
    marginRight: 8,
    marginBottom: 8,
  },
  chromaChipPreview: {
    width: 18,
    height: 18,
    borderRadius: 9,
    overflow: "hidden",
    marginRight: 8,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  chromaChipPreviewImage: {
    width: "100%",
    height: "100%",
  },
  chromaChipText: {
    fontSize: 11,
    fontWeight: "700",
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
  },
  segmentContainer: {
    position: "relative",
    height: 50,
    borderRadius: 25,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
  },
  segmentLayer: {
    ...StyleSheet.absoluteFill,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  segmentIndicator: {
    position: "absolute",
    left: 8,
    top: 6,
    bottom: 6,
    borderRadius: 19,
    backgroundColor: COLORS.PURE_WHITE,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  segmentLabel: {
    fontSize: 15,
    fontWeight: "700",
  },
  identityContainer: {
    flexDirection: "row",
    borderRadius: RADIUS.card,
    overflow: "hidden",
    borderWidth: 1,
  },
  identityImageFrame: {
    width: 150,
    height: 150,
    position: "relative",
  },
  identityImage: {
    width: "100%",
    height: "100%",
  },
  identityLevelBadge: {
    position: "absolute",
    right: 10,
    bottom: 10,
    minWidth: 48,
    height: 28,
    borderRadius: 999,
    paddingHorizontal: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(26, 29, 36, 0.86)",
  },
  identityLevelText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
    marginLeft: 4,
  },
  identityInfo: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
  },
  identityCardNameRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  identityTitle: {
    flex: 1,
    paddingRight: 8,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "700",
  },
  identityTitleAction: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: COLORS.SURFACE_MUTED,
  },
  identityActionText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 4,
  },
  identityActionLabel: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 10,
    fontWeight: "700",
  },
  identityActionValue: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
  },
  identityAccountLevel: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: "600",
  },
  sprayList: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  sprayCard: {
    width: "48%",
    marginBottom: 12,
    borderRadius: RADIUS.card,
    padding: 12,
    alignItems: "center",
    borderWidth: 1,
    backgroundColor: COLORS.SURFACE,
  },
  sprayImage: {
    width: 77,
    height: 77,
    marginBottom: 10,
  },
  sprayName: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 4,
    textAlign: "center",
  },
  spraySlot: {
    fontSize: 12,
    textAlign: "center",
    opacity: 0.8,
  },
  categorySection: {
    marginBottom: 24,
  },
  categoryTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
    marginLeft: 4,
  },
  weaponCard: {
    flexDirection: "row",
    marginBottom: 12,
    borderRadius: RADIUS.card,
    padding: 14,
    minHeight: 128,
    borderWidth: 1,
    alignItems: "center",
  },
  syncedWeaponCard: {
    padding: 12,
    minHeight: 112,
    borderRadius: 22,
  },
  weaponDetails: {
    flex: 1,
    marginRight: 12,
    justifyContent: "center",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 13,
  },
  weaponTags: {
    flexDirection: "row",
    marginTop: 4,
    flexWrap: "wrap",
  },
  weaponTag: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    marginRight: 6,
    marginBottom: 4,
    borderWidth: 1,
  },
  weaponTagText: {
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  weaponImageWrapper: {
    width: 116,
    height: 96,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 18,
    borderWidth: 1,
    padding: 10,
    overflow: "hidden",
  },
  syncedWeaponImageWrapper: {
    width: 104,
    height: 88,
    borderRadius: 20,
    padding: 8,
  },
  weaponImage: {
    width: "100%",
    height: "100%",
  },
  profileSkinCategoryRow: {
    paddingHorizontal: 16,
  },
  profileSkinCategoryTitleSwipeSurface: {
    alignSelf: "stretch",
    marginBottom: 8,
  },
  profileSkinCardLane: {
    flexDirection: "row",
  },
  profileSkinRowWhitespace: {
    flex: 1,
  },
  profileSkinCategorySpacer: {
    height: 16,
  },
  profileSkinCategoryTitle: {
    fontSize: 15,
    fontWeight: "800",
  },
  profileSkinRow: {
    gap: 8,
    paddingRight: 8,
  },
  profileSkinCard: {
    backgroundColor: COLORS.SURFACE,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 8,
    overflow: "hidden",
  },
  profileSkinVisual: {
    aspectRatio: 1.45,
    alignItems: "center",
    borderBottomWidth: 1,
    justifyContent: "center",
    padding: 8,
    position: "relative",
  },
  profileSkinImage: {
    width: "100%",
    height: "100%",
  },
  profileSkinTierBadge: {
    borderRadius: 4,
    left: 6,
    maxWidth: "58%",
    paddingHorizontal: 5,
    paddingVertical: 3,
    position: "absolute",
    top: 6,
    zIndex: 1,
  },
  profileSkinTierText: {
    fontSize: 8,
    fontWeight: "900",
  },
  profileSkinLevelBadge: {
    backgroundColor: COLORS.PURE_BLACK,
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 3,
    position: "absolute",
    right: 6,
    top: 6,
    zIndex: 1,
  },
  profileSkinLevelText: {
    color: COLORS.PURE_WHITE,
    fontSize: 8,
    fontWeight: "900",
  },
  profileSkinContent: {
    paddingHorizontal: 8,
    paddingTop: 7,
    paddingBottom: 8,
  },
  profileSkinWeaponName: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 9,
    fontWeight: "600",
    marginBottom: 2,
  },
  profileSkinName: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
    minHeight: 28,
  },
  searchBar: {
    flex: 1,
    borderRadius: 20,
    elevation: 0,
    borderWidth: 1,
  },
  collectionSearchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  collectionFilterRow: {
    paddingHorizontal: 16,
    paddingBottom: 10,
    paddingTop: 2,
  },
  collectionFilterChip: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: RADIUS.chip,
    backgroundColor: COLORS.SURFACE,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    marginRight: 8,
  },
  collectionFilterChipActive: {
    backgroundColor: COLORS.PURE_BLACK,
    borderColor: COLORS.PURE_BLACK,
  },
  collectionFilterChipText: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 12,
    fontWeight: "700",
  },
  collectionFilterChipTextActive: {
    color: COLORS.PURE_WHITE,
  },
  collectionRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 16,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  errorText: {
    fontSize: 16,
    textAlign: "center",
  },
  emptyText: {
    fontSize: 16,
    textAlign: "center",
    marginTop: 32,
  },
});
