import { Platform, StyleSheet } from "react-native";
export const STATS_COLORS = {
  page: "#090A0B",
  card: "#141414",
  cardSecondary: "#101010",
  row: "#111111",
  border: "#2A2A2A",
  borderSecondary: "#202020",
  divider: "#242424",
  text: "#F1F1F1",
  textSecondary: "#A0A0A0",
  textMuted: "#646464",
  accent: "#A56BFF",
  accentDark: "#603A96",
  accentSoft: "rgba(165, 107, 255, 0.14)",
  positive: "#00F58C",
  negative: "#FF3B47",
  warning: "#F6C84C",
  neutral: "#D6D6D6",
} as const;

// MONO_FONT: Font monospace theo nền tảng (Android/iOS/web)
export const MONO_FONT = Platform.select({
  android: "monospace",
  ios: "Menlo",
  web: "monospace",
});

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: STATS_COLORS.page,
  },
  screenContent: {
    paddingHorizontal: 6,
    paddingTop: 10,
    paddingBottom: 32,
  },
  card: {
    marginBottom: 10,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: STATS_COLORS.border,
    backgroundColor: STATS_COLORS.card,
    overflow: "hidden",
  },
  cardHeader: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: STATS_COLORS.divider,
  },
  cardHeaderTitleRow: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 1,
  },
  cardHeaderIcon: {
    width: 19,
    height: 19,
    marginRight: 7,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: STATS_COLORS.accentSoft,
  },
  cardHeaderTitle: {
    flexShrink: 1,
    color: STATS_COLORS.text,
    fontFamily: MONO_FONT,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "700",
    letterSpacing: 1.05,
  },
  headerMeta: {
    marginLeft: 8,
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.6,
    fontVariant: ["tabular-nums"],
  },
  performanceHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 6,
  },
  actBadge: {
    maxWidth: 62,
    marginRight: 5,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: STATS_COLORS.borderSecondary,
    backgroundColor: STATS_COLORS.cardSecondary,
  },
  actBadgeText: {
    color: STATS_COLORS.textSecondary,
    fontFamily: MONO_FONT,
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 0.35,
  },
  outlineButton: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 7,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: STATS_COLORS.accentDark,
  },
  outlineButtonText: {
    marginLeft: 4,
    color: STATS_COLORS.accent,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.55,
  },
  buttonPressed: {
    opacity: 0.75,
  },
  metricGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  metricCell: {
    width: "50%",
    minHeight: 62,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: STATS_COLORS.divider,
  },
  metricCellRight: {
    borderLeftWidth: 1,
    borderLeftColor: STATS_COLORS.divider,
  },
  metricCellBottom: {
    borderBottomWidth: 0,
  },
  metricLabel: {
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1,
  },
  metricValue: {
    marginTop: 6,
    fontFamily: MONO_FONT,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  tableTabs: {
    minHeight: 40,
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: STATS_COLORS.divider,
  },
  tableTab: {
    flex: 1,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  tableTabText: {
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.9,
  },
  tableTabTextActive: {
    color: STATS_COLORS.text,
  },
  tableTabLine: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 2,
    backgroundColor: "transparent",
  },
  tableTabLineActive: {
    backgroundColor: STATS_COLORS.accent,
  },
  tableHeaderRow: {
    minHeight: 27,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 9,
    backgroundColor: STATS_COLORS.cardSecondary,
    borderBottomWidth: 1,
    borderBottomColor: STATS_COLORS.borderSecondary,
  },
  tableHeaderText: {
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 0.45,
    textAlign: "right",
  },
  nameColumn: {
    flex: 0.51,
  },
  statColumn: {
    flex: 0.1225,
    minWidth: 0,
  },
  tableDataRow: {
    minHeight: 37,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 9,
    borderBottomWidth: 1,
    borderBottomColor: STATS_COLORS.borderSecondary,
    backgroundColor: STATS_COLORS.row,
  },
  tableNameCell: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 4,
  },
  agentAvatar: {
    width: 20,
    height: 20,
    marginRight: 6,
    borderRadius: 3,
    backgroundColor: STATS_COLORS.cardSecondary,
  },
  tableName: {
    minWidth: 0,
    flexShrink: 1,
    color: STATS_COLORS.text,
    fontSize: 10,
    fontWeight: "700",
  },
  gamesLabel: {
    marginLeft: 4,
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 7.5,
    fontVariant: ["tabular-nums"],
  },
  tableValue: {
    color: STATS_COLORS.neutral,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "700",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  emptyState: {
    minHeight: 74,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  emptyStateText: {
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "600",
    letterSpacing: 0.7,
    textAlign: "center",
  },
  recentRow: {
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 9,
    borderBottomWidth: 1,
    borderBottomColor: STATS_COLORS.borderSecondary,
    backgroundColor: STATS_COLORS.row,
  },
  recentDate: {
    width: "13%",
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 7.5,
    fontVariant: ["tabular-nums"],
  },
  recentRankCell: {
    width: "43%",
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
  },
  recentRankIcon: {
    width: 22,
    height: 22,
    marginRight: 5,
  },
  recentRankTextWrap: {
    minWidth: 0,
    flex: 1,
  },
  recentRankName: {
    color: STATS_COLORS.text,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "700",
  },
  recentMapName: {
    marginTop: 2,
    color: STATS_COLORS.textMuted,
    fontSize: 10,
  },
  recentResult: {
    width: "23%",
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "800",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  recentRr: {
    width: "21%",
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "700",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  activityBody: {
    paddingHorizontal: 9,
    paddingVertical: 10,
  },
  activityMonthRow: {
    flexDirection: "row",
    paddingLeft: 31,
    marginBottom: 5,
  },
  activityMonthText: {
    width: 15,
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 6.5,
  },
  activityGridRow: {
    flexDirection: "row",
  },
  activityDayLabels: {
    width: 31,
    height: 95,
    justifyContent: "space-around",
    paddingVertical: 3,
  },
  activityDayText: {
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 6.5,
  },
  activityWeeks: {
    flexDirection: "row",
    paddingRight: 2,
  },
  activityWeek: {
    width: 15,
    marginRight: 1,
  },
  activityCell: {
    width: 11,
    height: 11,
    marginBottom: 2,
    borderRadius: 2,
  },
  activityCellSelected: {
    borderWidth: 1,
    borderColor: STATS_COLORS.text,
  },
  activityFooter: {
    minHeight: 24,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 7,
  },
  activitySelection: {
    flex: 1,
    paddingRight: 8,
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 6.5,
    letterSpacing: 0.25,
  },
  activityLegend: {
    flexDirection: "row",
  },
  activityLegendItem: {
    alignItems: "center",
    marginLeft: 4,
  },
  activityLegendCell: {
    width: 8,
    height: 8,
    borderRadius: 2,
  },
  activityLegendText: {
    marginTop: 2,
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 5.5,
  },
  trendChart: {
    height: 104,
    marginHorizontal: 9,
    marginVertical: 8,
    position: "relative",
    overflow: "hidden",
  },
  trendGridLine: {
    position: "absolute",
    left: 8,
    right: 34,
    height: 1,
    backgroundColor: STATS_COLORS.borderSecondary,
  },
  trendPoint: {
    position: "absolute",
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: STATS_COLORS.accent,
  },
  trendAxisLabel: {
    position: "absolute",
    right: 0,
    width: 30,
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 7,
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  trendEmpty: {
    flex: 1,
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  rankSummaryGrid: {
    flexDirection: "row",
  },
  rankSummaryCell: {
    width: "50%",
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  rankSummaryCellRight: {
    borderLeftWidth: 1,
    borderLeftColor: STATS_COLORS.divider,
  },
  rankSummaryIcon: {
    width: 34,
    height: 34,
    marginRight: 8,
  },
  rankSummaryText: {
    minWidth: 0,
    flex: 1,
  },
  rankSummaryValue: {
    marginTop: 5,
    color: STATS_COLORS.text,
    fontFamily: MONO_FONT,
    fontSize: 11,
    fontWeight: "800",
  },
  detailRow: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#191919",
    backgroundColor: STATS_COLORS.row,
  },
  detailLabel: {
    color: STATS_COLORS.textSecondary,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.9,
  },
  detailValue: {
    color: STATS_COLORS.text,
    fontFamily: MONO_FONT,
    fontSize: 13,
    fontWeight: "800",
    fontVariant: ["tabular-nums"],
  },
  loadingBar: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: STATS_COLORS.border,
    backgroundColor: STATS_COLORS.card,
  },
  loadingDot: {
    width: 6,
    height: 6,
    marginRight: 8,
    borderRadius: 3,
    backgroundColor: STATS_COLORS.accent,
  },
  loadingText: {
    color: STATS_COLORS.textSecondary,
    fontFamily: MONO_FONT,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.7,
  },
  dashboardFooter: {
    marginTop: 3,
    color: STATS_COLORS.textMuted,
    fontFamily: MONO_FONT,
    fontSize: 7,
    lineHeight: 12,
    letterSpacing: 0.55,
    textAlign: "center",
  },
});
