import { StyleSheet } from "react-native";
import { COLORS, GLASS_MATERIAL, LAYOUT, RADIUS, SHADOWS, SPACING, TYPOGRAPHY } from "~/constants/DesignSystem";
import { FLAT_CARD_STYLE } from "~/components/ui/LiquidGlassSurface";

// Party uses existing semantic tokens; the reference's red maps to STATUS_BUSY.
export const PARTY_ACCENT = COLORS.STATUS_BUSY;
export const partyStyles = StyleSheet.create({
  sheet: {
    flex: 1,
    backgroundColor: COLORS.SURFACE,
    borderTopLeftRadius: RADIUS.screen,
    borderTopRightRadius: RADIUS.screen,
    overflow: "hidden",
  },
  content: {
    flexGrow: 1,
    padding: LAYOUT.compactScreenPadding,
    gap: SPACING.sm,
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
  },
  row: { flexDirection: "row", alignItems: "center", gap: SPACING.xs },
  spread: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: SPACING.xs },
  flexible: { flex: 1, minWidth: 0 },
  heading: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: TYPOGRAPHY.title,
    fontWeight: "800",
    letterSpacing: -1,
    flex: 1,
  },
  sectionTitle: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.titleSmall, fontWeight: "700", flexShrink: 1 },
  section: { gap: SPACING.sm },
  card: {
    ...FLAT_CARD_STYLE,
    borderRadius: RADIUS.xl,
  },
  cardContent: { padding: SPACING.sm, gap: SPACING.xs },
  flush: { padding: 0 },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: RADIUS.chip,
    backgroundColor: COLORS.BACKGROUND,
    alignItems: "center",
    justifyContent: "center",
  },
  primary: { backgroundColor: PARTY_ACCENT, borderRadius: RADIUS.chip, minHeight: 48 },
  primaryText: { color: COLORS.PURE_WHITE, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700" },
  smallPrimaryText: { color: COLORS.PURE_WHITE, fontSize: TYPOGRAPHY.bodySmall },
  quietButton: { backgroundColor: COLORS.SURFACE, borderRadius: RADIUS.chip, minHeight: 48 },
  accentText: { color: PARTY_ACCENT, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700" },
  link: { minHeight: 48, justifyContent: "center", flexShrink: 1 },
  title: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700" },
  queueTitle: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.titleSmall, fontWeight: "700", flex: 1 },
  secondary: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.bodySmall, flexShrink: 1 },
  caption: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.caption },
  error: { color: COLORS.WARNING, fontSize: TYPOGRAPHY.bodySmall, paddingVertical: SPACING.xs },
  disabled: { opacity: 0.5 },
  divider: { height: StyleSheet.hairlineWidth, backgroundColor: COLORS.BORDER_STRONG },
  teamContent: { padding: SPACING.xs },
  teamHeading: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700", padding: SPACING.xxs },
  teamEmpty: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.caption, padding: SPACING.xs },
  memberProfile: { flexDirection: "row", alignItems: "center", minHeight: 48, paddingVertical: SPACING.xs, paddingHorizontal: SPACING.xxs, gap: SPACING.xs },
  avatar: { width: 32, height: 32, borderRadius: RADIUS.sm, backgroundColor: COLORS.SURFACE_MUTED },
  avatarFallback: { alignItems: "center", justifyContent: "center" },
  nameRow: { flexDirection: "row", alignItems: "center", gap: SPACING.xxs, flexWrap: "wrap" },
  memberName: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodyCompact, fontWeight: "700", flexShrink: 1, maxWidth: "100%" },
  memberCaption: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.captionSmall, lineHeight: 16, flexShrink: 1 },
  badge: { borderRadius: RADIUS.chip, paddingHorizontal: SPACING.xxs, backgroundColor: COLORS.WARNING_SURFACE },
  badgeText: { color: PARTY_ACCENT, fontSize: TYPOGRAPHY.captionSmall, fontWeight: "700" },
  metadata: { flexDirection: "row", gap: SPACING.xxs, flexWrap: "wrap", marginTop: SPACING.xxs },
  rank: { width: 20, alignItems: "flex-end", justifyContent: "center", flexShrink: 0 },
  rankIcon: { width: 20, height: 20 },
  readyTouch: { minHeight: 48, minWidth: 60, alignItems: "center", justifyContent: "center" },
  friendList: { gap: SPACING.xs },
  friendCard: {
    ...FLAT_CARD_STYLE,
    width: 96,
    padding: SPACING.xs,
    gap: SPACING.xxs,
    alignItems: "center",
    borderWidth: 1,
    borderRadius: RADIUS.lg,
  },
  friendAvatar: { width: 48, height: 48, borderRadius: RADIUS.md, backgroundColor: COLORS.SURFACE_MUTED },
  presence: { position: "absolute", right: -2, bottom: -2, width: 14, height: 14, borderRadius: RADIUS.chip, borderWidth: 2, borderColor: COLORS.SURFACE },
  friendName: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700", maxWidth: "100%" },
  friendStatus: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.caption, lineHeight: 20,
    minHeight: 40, textAlign: "center", width: "100%", flexShrink: 1 },
  settingsRow: { minHeight: 56, padding: SPACING.xs, flexDirection: "row", alignItems: "center", gap: SPACING.xs },
  settingsLabel: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700", flexShrink: 1 },
  settingsValue: { color: PARTY_ACCENT, fontSize: TYPOGRAPHY.bodySmall, flex: 1, textAlign: "right" },
  backdrop: { flex: 1, backgroundColor: COLORS.MODAL_BACKDROP, justifyContent: "flex-end", padding: SPACING.md },
  dialog: { backgroundColor: COLORS.SURFACE, borderRadius: RADIUS.screen, padding: SPACING.sm, gap: SPACING.xs, maxHeight: "90%", width: "100%", maxWidth: 520, alignSelf: "center" },
  inviteButtons: { flexDirection: "row", flexWrap: "wrap", gap: SPACING.xs },
  codePanel: { backgroundColor: COLORS.SURFACE },
  codePanelContent: { padding: SPACING.sm, gap: SPACING.xxs },
  codeHeader: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: SPACING.xs },
  codeHeaderLabel: { flexDirection: "row", alignItems: "center", gap: SPACING.xs,
    flexGrow: 1, flexShrink: 1, flexBasis: "auto", minWidth: 0, maxWidth: "100%" },
  codeValueRow: { flexDirection: "row", alignItems: "center", gap: SPACING.xs, minHeight: 48 },
  codeScroller: { flex: 1, minWidth: 0 },
  codeScrollContent: { alignItems: "center", paddingVertical: SPACING.xxs },
  codeValue: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.title, fontWeight: "700", fontVariant: ["tabular-nums"] },
  codeTools: { flexDirection: "row", gap: SPACING.xs },
  codeIconButton: { minWidth: 48, minHeight: 48, alignItems: "center", justifyContent: "center", borderRadius: RADIUS.button },
  codeGenerate: { minHeight: 48, minWidth: 48, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xs,
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: SPACING.xs, alignSelf: "flex-start", flexShrink: 1, borderRadius: RADIUS.button },
  codeGenerateText: { flexShrink: 1 },
  codeGeneratePrimary: { backgroundColor: PARTY_ACCENT },
  codeGenerateQuiet: { marginLeft: "auto" },
  codeFormActions: { flexDirection: "row", gap: SPACING.xs },
  codeFormActionsStacked: { flexDirection: "column" },
  codeFormAction: { flexGrow: 1, flexBasis: 0, minWidth: 48, minHeight: 48, paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.xxs, alignItems: "center", justifyContent: "center", borderRadius: RADIUS.button },
  codeActionText: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "600", textAlign: "center", flexShrink: 1 },
  compactButton: { minHeight: 48, minWidth: 48, flexGrow: 1, flexBasis: "auto", borderRadius: RADIUS.chip },
  formKeyboard: { flex: 1 },
  formContent: { gap: SPACING.xs },
  formInput: { minHeight: 48, padding: SPACING.sm, borderWidth: 1, borderColor: COLORS.BORDER_STRONG, borderRadius: RADIUS.md,
    backgroundColor: COLORS.BACKGROUND, color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall },
  option: { minHeight: 52, flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: SPACING.sm, gap: SPACING.xs, borderRadius: RADIUS.md },
  selected: { backgroundColor: COLORS.WARNING_SURFACE, borderColor: PARTY_ACCENT },
  modalScreen: { flex: 1, backgroundColor: COLORS.MODAL_BACKDROP, padding: SPACING.md, justifyContent: "center" },
  agentDialog: { flexShrink: 1, backgroundColor: GLASS_MATERIAL.denseSurface, borderRadius: RADIUS.screen, padding: SPACING.md, gap: SPACING.md, maxHeight: "100%", width: "100%", maxWidth: 520, alignSelf: "center", ...SHADOWS.sm },
  agentGrid: { flexGrow: 0, flexShrink: 1 },
  agentColumns: { gap: SPACING.xs },
  agentContent: { gap: SPACING.xs },
  agentTile: { ...FLAT_CARD_STYLE, flex: 1, maxWidth: "33.333%", minWidth: 0, padding: SPACING.xs, gap: SPACING.xxs, borderRadius: RADIUS.md, alignItems: "center", minHeight: 112 },
  agentPortrait: { width: 64, height: 64, borderRadius: RADIUS.md },
  agentName: { fontSize: TYPOGRAPHY.bodySmall, color: COLORS.TEXT_PRIMARY, fontWeight: "700", maxWidth: "100%" },
});
