import { StyleSheet } from "react-native";
import { COLORS, GLASS_MATERIAL, LAYOUT, RADIUS, SHADOWS, SPACING, TYPOGRAPHY } from "~/constants/DesignSystem";

// Party uses existing semantic tokens; the reference's red maps to STATUS_BUSY.
export const PARTY_ACCENT = COLORS.STATUS_BUSY;
export const partyStyles = StyleSheet.create({
  sheet: {
    flex: 1,
    backgroundColor: COLORS.SURFACE,
    borderTopLeftRadius: RADIUS.screen,
    borderTopRightRadius: RADIUS.screen,
    overflow: "hidden",
  },
  content: {
    flexGrow: 1,
    padding: LAYOUT.compactScreenPadding,
    gap: SPACING.sm,
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
  },
  row: { flexDirection: "row", alignItems: "center", gap: SPACING.xs },
  spread: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: SPACING.xs },
  flexible: { flex: 1, minWidth: 0 },
  heading: {
    color: COLORS.TEXT_PRIMARY,
    fontSize: TYPOGRAPHY.title,
    fontWeight: "800",
    letterSpacing: -1,
    flex: 1,
  },
  sectionTitle: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.titleSmall, fontWeight: "700", flexShrink: 1 },
  section: { gap: SPACING.sm },
  card: {
    backgroundColor: GLASS_MATERIAL.surface,
    borderColor: GLASS_MATERIAL.border,
    borderRadius: RADIUS.xl,
    ...SHADOWS.xs,
  },
  cardContent: { padding: SPACING.sm, gap: SPACING.xs },
  flush: { padding: 0 },
  iconButton: {
    width: 48,
    height: 48,
    borderRadius: RADIUS.chip,
    backgroundColor: COLORS.BACKGROUND,
    alignItems: "center",
    justifyContent: "center",
  },
  primary: { backgroundColor: PARTY_ACCENT, borderRadius: RADIUS.chip, minHeight: 48 },
  primaryText: { color: COLORS.PURE_WHITE, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700" },
  smallPrimaryText: { color: COLORS.PURE_WHITE, fontSize: TYPOGRAPHY.bodySmall },
  quietButton: { backgroundColor: COLORS.SURFACE, borderRadius: RADIUS.chip, minHeight: 48 },
  accentText: { color: PARTY_ACCENT, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700" },
  link: { minHeight: 48, justifyContent: "center", flexShrink: 1 },
  title: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700" },
  queueTitle: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.titleSmall, fontWeight: "700", flex: 1 },
  secondary: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.bodySmall, flexShrink: 1 },
  caption: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.caption },
  error: { color: COLORS.WARNING, fontSize: TYPOGRAPHY.bodySmall, paddingVertical: SPACING.xs },
  disabled: { opacity: 0.5 },
  divider: { height: StyleSheet.hairlineWidth, backgroundColor: COLORS.BORDER_STRONG },
  memberProfile: { flexDirection: "row", alignItems: "center", padding: SPACING.xs, gap: SPACING.xs, minHeight: 72 },
  avatar: { width: 48, height: 48, borderRadius: RADIUS.md, backgroundColor: COLORS.SURFACE_MUTED },
  avatarFallback: { alignItems: "center", justifyContent: "center" },
  nameRow: { flexDirection: "row", alignItems: "center", gap: SPACING.xxs, flexWrap: "wrap" },
  memberName: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700", flexShrink: 1, maxWidth: "100%" },
  badge: { borderRadius: RADIUS.chip, paddingHorizontal: SPACING.xs, paddingVertical: SPACING.xxs, backgroundColor: COLORS.WARNING_SURFACE },
  badgeText: { color: PARTY_ACCENT, fontSize: TYPOGRAPHY.caption, fontWeight: "700" },
  metadata: { flexDirection: "row", gap: SPACING.xxs, flexWrap: "wrap", marginTop: SPACING.xxs },
  rank: { maxWidth: 92, flexShrink: 1, alignItems: "flex-end", gap: SPACING.xxs },
  rankIcon: { width: 40, height: 40 },
  readyRow: { paddingHorizontal: SPACING.xs, minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  readyTouch: { minHeight: 48, minWidth: 60, alignItems: "center", justifyContent: "center" },
  friendList: { gap: SPACING.xs },
  friendCard: {
    width: 76,
    padding: SPACING.xs,
    gap: SPACING.xxs,
    alignItems: "center",
    backgroundColor: GLASS_MATERIAL.surface,
    borderWidth: 1,
    borderColor: GLASS_MATERIAL.border,
    borderRadius: RADIUS.lg,
    ...SHADOWS.xs,
  },
  friendAvatar: { width: 48, height: 48, borderRadius: RADIUS.md, backgroundColor: COLORS.SURFACE_MUTED },
  presence: { position: "absolute", right: -2, bottom: -2, width: 14, height: 14, borderRadius: RADIUS.chip, borderWidth: 2, borderColor: COLORS.SURFACE },
  friendName: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700", maxWidth: "100%" },
  settingsRow: { minHeight: 56, padding: SPACING.xs, flexDirection: "row", alignItems: "center", gap: SPACING.xs },
  settingsLabel: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "700", flexShrink: 1 },
  settingsValue: { color: PARTY_ACCENT, fontSize: TYPOGRAPHY.bodySmall, flex: 1, textAlign: "right" },
  backdrop: { flex: 1, backgroundColor: COLORS.MODAL_BACKDROP, justifyContent: "flex-end", padding: SPACING.md },
  dialog: { backgroundColor: COLORS.SURFACE, borderRadius: RADIUS.screen, padding: SPACING.sm, gap: SPACING.xs, maxHeight: "90%", width: "100%", maxWidth: 520, alignSelf: "center" },
  inviteButtons: { flexDirection: "row", flexWrap: "wrap", gap: SPACING.xs },
  codePanel: { backgroundColor: GLASS_MATERIAL.denseSurface },
  codePanelContent: { padding: SPACING.sm, gap: SPACING.xxs },
  codeHeader: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: SPACING.xs },
  codeHeaderLabel: { flexDirection: "row", alignItems: "center", gap: SPACING.xs,
    flexGrow: 1, flexShrink: 1, flexBasis: "auto", minWidth: 0, maxWidth: "100%" },
  codeValueRow: { flexDirection: "row", alignItems: "center", gap: SPACING.xs, minHeight: 48 },
  codeScroller: { flex: 1, minWidth: 0 },
  codeScrollContent: { alignItems: "center", paddingVertical: SPACING.xxs },
  codeValue: { color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.title, fontWeight: "700", fontVariant: ["tabular-nums"] },
  codeTools: { flexDirection: "row", gap: SPACING.xs },
  codeIconButton: { minWidth: 48, minHeight: 48, alignItems: "center", justifyContent: "center", borderRadius: RADIUS.button },
  codeGenerate: { minHeight: 48, minWidth: 48, paddingHorizontal: SPACING.sm, paddingVertical: SPACING.xs,
    flexDirection: "row", alignItems: "center", justifyContent: "center", gap: SPACING.xs, alignSelf: "flex-start", flexShrink: 1, borderRadius: RADIUS.button },
  codeGenerateText: { flexShrink: 1 },
  codeGeneratePrimary: { backgroundColor: PARTY_ACCENT },
  codeGenerateQuiet: { marginLeft: "auto" },
  codeFormActions: { flexDirection: "row", gap: SPACING.xs },
  codeFormActionsStacked: { flexDirection: "column" },
  codeFormAction: { flexGrow: 1, flexBasis: 0, minWidth: 48, minHeight: 48, paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.xxs, alignItems: "center", justifyContent: "center", borderRadius: RADIUS.button },
  codeActionText: { color: COLORS.TEXT_SECONDARY, fontSize: TYPOGRAPHY.bodySmall, fontWeight: "600", textAlign: "center", flexShrink: 1 },
  compactButton: { minHeight: 48, minWidth: 48, flexGrow: 1, flexBasis: "auto", borderRadius: RADIUS.chip },
  formKeyboard: { flex: 1 },
  formContent: { gap: SPACING.xs },
  formInput: { minHeight: 48, padding: SPACING.sm, borderWidth: 1, borderColor: COLORS.BORDER_STRONG, borderRadius: RADIUS.md,
    backgroundColor: COLORS.BACKGROUND, color: COLORS.TEXT_PRIMARY, fontSize: TYPOGRAPHY.bodySmall },
  option: { minHeight: 52, flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: SPACING.sm, gap: SPACING.xs, borderRadius: RADIUS.md },
  selected: { backgroundColor: COLORS.WARNING_SURFACE, borderColor: PARTY_ACCENT },
  modalScreen: { flex: 1, backgroundColor: COLORS.MODAL_BACKDROP, padding: SPACING.md, justifyContent: "center" },
  agentDialog: { flexShrink: 1, backgroundColor: GLASS_MATERIAL.denseSurface, borderRadius: RADIUS.screen, padding: SPACING.md, gap: SPACING.md, maxHeight: "100%", width: "100%", maxWidth: 520, alignSelf: "center", ...SHADOWS.sm },
  agentGrid: { flexGrow: 0, flexShrink: 1 },
  agentColumns: { gap: SPACING.xs },
  agentContent: { gap: SPACING.xs },
  agentTile: { flex: 1, maxWidth: "33.333%", minWidth: 0, padding: SPACING.xs, gap: SPACING.xxs, borderRadius: RADIUS.md, borderWidth: 1, borderColor: GLASS_MATERIAL.border, backgroundColor: GLASS_MATERIAL.surface, alignItems: "center", minHeight: 112, ...SHADOWS.xs },
  agentPortrait: { width: 64, height: 64, borderRadius: RADIUS.md },
  agentName: { fontSize: TYPOGRAPHY.bodySmall, color: COLORS.TEXT_PRIMARY, fontWeight: "700", maxWidth: "100%" },
});
