import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeAlert,
  BadgeCheck,
  BatteryWarning,
  Calendar,
  CalendarDays,
  ChartBar,
  ChartLine,
  ChartNoAxesCombined,
  ChartNoAxesGantt,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleArrowUp,
  CircleCheck,
  CircleDashed,
  CircleHelp,
  CircleUserRound,
  CircleX,
  Clock,
  ClipboardCheck,
  Coins,
  Copy,
  Crosshair,
  DatabaseX,
  Download,
  Gem,
  Globe,
  Grid3X3,
  Heart,
  History,
  ImageOff,
  Images,
  Info,
  Languages,
  Layers3,
  LayoutDashboard,
  List,
  LoaderCircle,
  Map,
  Menu,
  MoonStar,
  Package,
  Palette,
  Pencil,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingBag,
  Skull,
  Sparkles,
  SprayCan,
  Star,
  ScrollText,
  Swords,
  Target,
  Timer,
  Trophy,
  User,
  Users,
  Waypoints,
  X,
} from "lucide";
import type { AppIconDefinition } from "~/components/ui/app-icon-types";

export const APP_ICON_REGISTRY = {
  unknown: { kind: "morph", icon: CircleHelp },
  menu: { kind: "morph", icon: Menu },
  close: { kind: "morph", icon: X },
  search: { kind: "morph", icon: Search },
  back: { kind: "morph", icon: ArrowLeft },
  forward: { kind: "morph", icon: ArrowRight },
  chevronLeft: { kind: "morph", icon: ChevronLeft },
  chevronRight: { kind: "morph", icon: ChevronRight },
  chevronUp: { kind: "morph", icon: ChevronUp },
  chevronDown: { kind: "morph", icon: ChevronDown },
  refresh: { kind: "morph", icon: RefreshCw },
  loading: { kind: "morph", icon: LoaderCircle },
  check: { kind: "morph", icon: Check },
  success: { kind: "morph", icon: CircleCheck },
  error: { kind: "morph", icon: CircleX },
  info: { kind: "morph", icon: Info },
  account: { kind: "morph", icon: User },
  accountGroup: { kind: "morph", icon: Users },
  settings: { kind: "morph", icon: Settings },
  shop: { kind: "morph", icon: ShoppingBag },
  grid: { kind: "morph", icon: Grid3X3 },
  heart: { kind: "morph", icon: Heart },
  heartFilled: { kind: "morph", icon: Heart, filled: true },
  calendar: { kind: "morph", icon: Calendar },
  clock: { kind: "morph", icon: Clock },
  share: { kind: "morph", icon: Share2 },
  copy: { kind: "morph", icon: Copy },
  send: { kind: "morph", icon: Send },
  download: { kind: "morph", icon: Download },
  edit: { kind: "morph", icon: Pencil },
  globe: { kind: "morph", icon: Globe },
  map: { kind: "morph", icon: Map },
  target: { kind: "morph", icon: Target },
  chartLine: { kind: "morph", icon: ChartLine },
  chartBar: { kind: "morph", icon: ChartBar },
  databaseOff: { kind: "morph", icon: DatabaseX },
  navStore: { kind: "morph", icon: Package },
  navShop: { kind: "morph", icon: ShoppingBag },
  navProfile: { kind: "morph", icon: CircleUserRound },
  navNightMarket: { kind: "morph", icon: MoonStar },
  navMore: { kind: "morph", icon: Grid3X3 },
  language: { kind: "morph", icon: Languages },
  batteryWarning: { kind: "morph", icon: BatteryWarning },
  bundle: { kind: "morph", icon: Package },
  timer: { kind: "morph", icon: Timer },
  update: { kind: "morph", icon: Download },
  updateChecking: { kind: "morph", icon: LoaderCircle },
  imageGrid: { kind: "morph", icon: Images },
  equipmentProfile: {
    kind: "legacy",
    legacyName: "shield-account-outline",
  },
  playerStats: { kind: "morph", icon: ChartNoAxesCombined },
  region: { kind: "morph", icon: Globe },
  accountSynced: { kind: "morph", icon: BadgeCheck },
  accountWarning: { kind: "morph", icon: BadgeAlert },
  rank: { kind: "morph", icon: Star },
  peakRank: { kind: "morph", icon: Trophy },
  collection: { kind: "morph", icon: Images },
  skin: { kind: "morph", icon: Sparkles },
  loadout: { kind: "morph", icon: Layers3 },
  spray: { kind: "morph", icon: SprayCan },
  flex: { kind: "morph", icon: Waypoints },
  selected: { kind: "morph", icon: CircleCheck },
  unselected: { kind: "morph", icon: Circle },
  overview: { kind: "morph", icon: LayoutDashboard },
  details: { kind: "morph", icon: List },
  season: { kind: "morph", icon: CalendarDays },
  export: { kind: "morph", icon: Download },
  emptyData: { kind: "morph", icon: DatabaseX },
  sortAscending: { kind: "morph", icon: ArrowUp },
  sortDescending: { kind: "morph", icon: ArrowDown },
  wishlist: { kind: "morph", icon: Heart },
  wishlistFilled: { kind: "morph", icon: Heart, filled: true },
  upgrade: { kind: "morph", icon: CircleArrowUp },
  palette: { kind: "morph", icon: Palette },
  timeline: { kind: "morph", icon: ChartNoAxesGantt },
  contract: { kind: "morph", icon: ScrollText },
  mission: { kind: "morph", icon: ClipboardCheck },
  leaderboardSeason: { kind: "morph", icon: Trophy },
  nightMarket: { kind: "morph", icon: MoonStar },
  crosshair: { kind: "morph", icon: Crosshair },
  accessory: { kind: "morph", icon: Gem },
  history: { kind: "morph", icon: History },
  match: { kind: "morph", icon: Swords },
  skull: { kind: "morph", icon: Skull },
  economy: { kind: "morph", icon: Coins },
  performance: { kind: "morph", icon: ChartNoAxesCombined },
  retry: { kind: "morph", icon: RefreshCw },
  emptyImage: { kind: "morph", icon: ImageOff },
  completed: { kind: "morph", icon: CircleCheck },
  incomplete: { kind: "morph", icon: CircleDashed },
  roundElimination: { kind: "legacy", legacyName: "crosshairs-gps" },
  roundSpikeDefused: {
    kind: "legacy",
    legacyName: "shield-check-outline",
  },
  roundSpikeDetonated: { kind: "legacy", legacyName: "bomb" },
  roundTimeExpired: { kind: "legacy", legacyName: "timer-sand" },
  roundSurrender: { kind: "legacy", legacyName: "flag-outline" },
  objectiveCrosshair: { kind: "legacy", legacyName: "crosshairs-gps" },
  shield: { kind: "legacy", legacyName: "shield-account-outline" },
  weaponPistol: { kind: "legacy", legacyName: "pistol" },
  combatSword: { kind: "legacy", legacyName: "sword-cross" },
} as const satisfies Record<string, AppIconDefinition>;

export type AppIconName = keyof typeof APP_ICON_REGISTRY;

export function resolveAppIconName(value: unknown): AppIconName {
  if (
    typeof value === "string" &&
    Object.prototype.hasOwnProperty.call(APP_ICON_REGISTRY, value)
  ) {
    return value as AppIconName;
  }

  return "unknown";
}

export function resolveAppIcon(name: AppIconName): AppIconDefinition {
  return APP_ICON_REGISTRY[resolveAppIconName(name)];
}
