import { StyleSheet } from "react-native";

export const TRACKER_COLORS = {
  background: "#07101D",
  panel: "#0C1828",
  panelStrong: "#101F32",
  border: "#20344A",
  borderSoft: "rgba(111, 143, 174, 0.2)",
  text: "#F2F7FC",
  muted: "#8496AA",
  faint: "#51657A",
  cyan: "#36D5ED",
  cyanSoft: "rgba(54, 213, 237, 0.12)",
  red: "#FF5E69",
  redSoft: "rgba(255, 94, 105, 0.12)",
  success: "#52D99B",
  warning: "#F5C66A",
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: TRACKER_COLORS.background,
  },
  sessionScroll: {
    flex: 1,
  },
  sessionScrollContent: {
    flexGrow: 1,
  },
  landscapeContent: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 7,
  },
  landscapeContentTight: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 5,
  },
  trackerHeader: {
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.border,
    backgroundColor: TRACKER_COLORS.panelStrong,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 7,
  },
  trackerHeaderTight: {
    height: 46,
  },
  headerMapImage: {
    ...StyleSheet.absoluteFill,
    opacity: 0.28,
  },
  headerScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(7, 16, 29, 0.72)",
  },
  headerPlayer: {
    zIndex: 1,
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  headerAction: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(9, 20, 34, 0.82)",
    borderWidth: 1,
    borderColor: TRACKER_COLORS.border,
  },
  headerActionPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.96 }],
  },
  headerAvatar: {
    width: 34,
    height: 34,
    borderRadius: 8,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TRACKER_COLORS.panel,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.cyan,
  },
  headerAvatarImage: {
    width: 31,
    height: 31,
  },
  headerPlayerText: {
    flex: 1,
    minWidth: 0,
  },
  headerPlayerName: {
    color: TRACKER_COLORS.text,
    fontSize: 12,
    fontWeight: "800",
  },
  headerPlayerMeta: {
    marginTop: 2,
    color: TRACKER_COLORS.muted,
    fontSize: 9,
    fontWeight: "600",
  },
  headerMatch: {
    zIndex: 1,
    flex: 0.9,
    minWidth: 0,
    alignItems: "center",
    paddingHorizontal: 8,
  },
  headerMapName: {
    color: TRACKER_COLORS.text,
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  headerQueue: {
    marginTop: 1,
    color: TRACKER_COLORS.muted,
    fontSize: 9,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  headerActions: {
    zIndex: 1,
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 7,
  },
  statsModeToggle: {
    minWidth: 58,
    minHeight: 28,
    paddingHorizontal: 8,
    borderRadius: 7,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backgroundColor: TRACKER_COLORS.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(54, 213, 237, 0.42)",
  },
  statsModeToggleMatch: {
    backgroundColor: TRACKER_COLORS.redSoft,
    borderColor: "rgba(255, 94, 105, 0.46)",
  },
  statsModeToggleText: {
    color: TRACKER_COLORS.cyan,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.35,
  },
  statsModeToggleTextMatch: {
    color: TRACKER_COLORS.red,
  },
  liveState: {
    maxWidth: 135,
    minHeight: 28,
    paddingHorizontal: 9,
    borderRadius: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(9, 20, 34, 0.82)",
    borderWidth: 1,
    borderColor: TRACKER_COLORS.borderSoft,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  liveStateText: {
    flexShrink: 1,
    color: TRACKER_COLORS.text,
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  summaryBar: {
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.borderSoft,
    backgroundColor: TRACKER_COLORS.panel,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  summaryBarTight: {
    height: 30,
  },
  summaryItem: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  summaryDivider: {
    width: 1,
    height: 15,
    backgroundColor: TRACKER_COLORS.borderSoft,
  },
  summaryValue: {
    maxWidth: "68%",
    color: TRACKER_COLORS.text,
    fontSize: 10,
    fontWeight: "800",
  },
  summaryLabel: {
    color: TRACKER_COLORS.muted,
    fontSize: 7,
    fontWeight: "800",
  },
  matchBoard: {
    flex: 1,
    minHeight: 0,
    flexDirection: "row",
    gap: 8,
  },
  teamPanel: {
    flex: 1,
    minWidth: 0,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.border,
    borderTopWidth: 2,
    overflow: "hidden",
    backgroundColor: TRACKER_COLORS.panel,
  },
  teamHeader: {
    height: 29,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 9,
    borderBottomWidth: 1,
    borderBottomColor: TRACKER_COLORS.borderSoft,
  },
  teamTitleGroup: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  teamDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  teamTitle: {
    maxWidth: "60%",
    color: TRACKER_COLORS.text,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  sideLabel: {
    fontSize: 8,
    fontWeight: "900",
  },
  teamCount: {
    color: TRACKER_COLORS.muted,
    fontSize: 9,
    fontWeight: "800",
  },
  teamList: {
    flex: 1,
    minHeight: 0,
    padding: 3,
  },
  playerRow: {
    flex: 1,
    minHeight: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderLeftWidth: 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: TRACKER_COLORS.borderSoft,
    backgroundColor: "rgba(255, 255, 255, 0.012)",
  },
  playerRowPressed: {
    backgroundColor: "rgba(255, 255, 255, 0.07)",
  },
  emptyPlayerSlot: {
    flex: 1,
    minHeight: 0,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: TRACKER_COLORS.borderSoft,
  },
  agentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 8,
    flexShrink: 0,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TRACKER_COLORS.panelStrong,
    borderWidth: 1,
  },
  agentImage: {
    width: 33,
    height: 33,
  },
  playerIdentity: {
    flex: 1,
    minWidth: 58,
  },
  playerNameLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  playerName: {
    flexShrink: 1,
    color: TRACKER_COLORS.text,
    fontSize: 10,
    fontWeight: "800",
  },
  youBadge: {
    borderRadius: 3,
    paddingHorizontal: 3,
    paddingVertical: 1,
  },
  youBadgeText: {
    color: TRACKER_COLORS.background,
    fontSize: 6,
    fontWeight: "900",
  },
  agentName: {
    maxWidth: 50,
    flexShrink: 1,
    color: TRACKER_COLORS.muted,
    fontSize: 7,
    fontWeight: "600",
  },
  playerMetaLine: {
    marginTop: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  currentRankInline: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    paddingLeft: 3,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: TRACKER_COLORS.border,
  },
  currentRankIcon: {
    width: 12,
    height: 12,
    flexShrink: 0,
  },
  currentRankIconPlaceholder: {
    width: 12,
    height: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  currentRankText: {
    flex: 1,
    color: TRACKER_COLORS.text,
    fontSize: 7,
    fontWeight: "700",
  },
  competitiveMetrics: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  competitiveMetric: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 2,
  },
  competitiveMetricLabel: {
    color: TRACKER_COLORS.muted,
    fontSize: 7,
    fontWeight: "800",
  },
  competitiveMetricValue: {
    color: TRACKER_COLORS.text,
    fontSize: 9,
    fontWeight: "900",
  },
  matchMetricValue: {
    color: TRACKER_COLORS.red,
  },
  peakRankEnd: {
    width: 80,
    minWidth: 0,
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "center",
    paddingLeft: 5,
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: TRACKER_COLORS.borderSoft,
  },
  peakRankLabel: {
    color: TRACKER_COLORS.muted,
    fontSize: 6,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  peakRankLine: {
    maxWidth: "100%",
    marginTop: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 2,
  },
  peakRankIcon: {
    width: 17,
    height: 17,
    flexShrink: 0,
  },
  peakRankName: {
    flexShrink: 1,
    color: TRACKER_COLORS.text,
    fontSize: 7,
    fontWeight: "800",
  },
  peakRankSeason: {
    maxWidth: "100%",
    color: TRACKER_COLORS.muted,
    fontSize: 6,
    fontWeight: "600",
  },
  emptyRoster: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  emptyRosterText: {
    maxWidth: 180,
    textAlign: "center",
    color: TRACKER_COLORS.muted,
    fontSize: 10,
  },
  emptyState: {
    flex: 1,
    minHeight: 0,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.border,
    backgroundColor: TRACKER_COLORS.panel,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 14,
  },
  emptyStateText: {
    maxWidth: 430,
  },
  emptyStateTitle: {
    color: TRACKER_COLORS.text,
    fontSize: 16,
    fontWeight: "900",
  },
  emptyStateSubtitle: {
    marginTop: 4,
    color: TRACKER_COLORS.muted,
    fontSize: 11,
    lineHeight: 15,
  },
  orientationLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TRACKER_COLORS.background,
  },
  modalRoot: {
    ...StyleSheet.absoluteFill,
    zIndex: 50,
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    backgroundColor: "rgba(2, 7, 13, 0.78)",
  },
  playerModal: {
    width: "100%",
    maxWidth: 590,
    maxHeight: "92%",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.border,
    backgroundColor: TRACKER_COLORS.panelStrong,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
  },
  modalHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  modalModeSwitch: {
    padding: 2,
    borderRadius: 8,
    flexDirection: "row",
    backgroundColor: TRACKER_COLORS.panel,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.border,
  },
  modalModeButton: {
    minWidth: 47,
    minHeight: 28,
    paddingHorizontal: 7,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  modalModeButtonCompetitive: {
    backgroundColor: TRACKER_COLORS.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(54, 213, 237, 0.42)",
  },
  modalModeButtonMatch: {
    backgroundColor: TRACKER_COLORS.redSoft,
    borderWidth: 1,
    borderColor: "rgba(255, 94, 105, 0.46)",
  },
  modalModeText: {
    color: TRACKER_COLORS.muted,
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  modalModeTextCompetitive: {
    color: TRACKER_COLORS.cyan,
  },
  modalModeTextMatch: {
    color: TRACKER_COLORS.red,
  },
  modalIdentity: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  modalAvatar: {
    width: 50,
    height: 50,
    borderRadius: 12,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TRACKER_COLORS.panel,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.cyan,
  },
  modalAvatarImage: {
    width: 46,
    height: 46,
  },
  modalTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  modalTitle: {
    color: TRACKER_COLORS.text,
    fontSize: 17,
    fontWeight: "900",
  },
  modalSubtitle: {
    marginTop: 3,
    color: TRACKER_COLORS.muted,
    fontSize: 10,
    fontWeight: "600",
  },
  modalClose: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: TRACKER_COLORS.panel,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.border,
  },
  modalRankGrid: {
    marginTop: 12,
    flexDirection: "row",
    gap: 8,
  },
  modalRankCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 74,
    borderRadius: 10,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: TRACKER_COLORS.panel,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.borderSoft,
  },
  modalRankIcon: {
    width: 38,
    height: 38,
  },
  modalCardLabel: {
    color: TRACKER_COLORS.muted,
    fontSize: 8,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  modalCardValue: {
    marginTop: 2,
    color: TRACKER_COLORS.text,
    fontSize: 13,
    fontWeight: "900",
  },
  modalCardMeta: {
    marginTop: 2,
    color: TRACKER_COLORS.cyan,
    fontSize: 9,
    fontWeight: "700",
  },
  modalStats: {
    marginTop: 8,
    borderRadius: 10,
    flexDirection: "row",
    backgroundColor: TRACKER_COLORS.panel,
    borderWidth: 1,
    borderColor: TRACKER_COLORS.borderSoft,
  },
  modalStat: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: TRACKER_COLORS.border,
  },
  modalStatValue: {
    color: TRACKER_COLORS.text,
    fontSize: 13,
    fontWeight: "900",
  },
  modalStatLabel: {
    marginTop: 2,
    color: TRACKER_COLORS.muted,
    fontSize: 7,
    fontWeight: "800",
  },
  modalRecentForm: {
    marginTop: 8,
    minHeight: 36,
    paddingHorizontal: 10,
    borderRadius: 9,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    backgroundColor: "rgba(9, 20, 34, 0.72)",
    borderWidth: 1,
    borderColor: TRACKER_COLORS.borderSoft,
  },
  modalRecentInfo: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  modalRecentLabel: {
    color: TRACKER_COLORS.muted,
    fontSize: 8,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  modalResults: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  modalResultBadge: {
    width: 18,
    height: 18,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  modalResultWin: {
    backgroundColor: "rgba(82, 217, 155, 0.16)",
    borderColor: "rgba(82, 217, 155, 0.42)",
  },
  modalResultLoss: {
    backgroundColor: TRACKER_COLORS.redSoft,
    borderColor: "rgba(255, 94, 105, 0.42)",
  },
  modalResultDraw: {
    backgroundColor: "rgba(132, 150, 170, 0.12)",
    borderColor: "rgba(132, 150, 170, 0.3)",
  },
  modalResultText: {
    color: TRACKER_COLORS.text,
    fontSize: 8,
    fontWeight: "900",
  },
  modalRrDelta: {
    fontSize: 11,
    fontWeight: "900",
  },
  modalRrPositive: {
    color: TRACKER_COLORS.success,
  },
  modalRrNegative: {
    color: TRACKER_COLORS.red,
  },
  modalRrNeutral: {
    color: TRACKER_COLORS.muted,
  },
  privateNotice: {
    marginTop: 8,
    minHeight: 30,
    borderRadius: 8,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(245, 198, 106, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(245, 198, 106, 0.2)",
  },
  privateNoticeText: {
    flex: 1,
    color: TRACKER_COLORS.muted,
    fontSize: 9,
    fontWeight: "600",
  },
});
